# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
monocular:
  enabled: false
docker-registry:
  enabled: false
controllerteam:
  enabled: false
controllerworkflow:
  enabled: false
controllercommitstatus:
  enabled: false
controllerrole:
  enabled: false
extensions:
  enabled: false
gcpreviews:
  cronjob:
    enabled: false
gcactivities:
  cronjob:
    enabled: false
  serviceaccount:
    enabled: false
  role:
    enabled: false
  clusterrole:
    enabled: true
gcpods:
  cronjob:
    enabled: false
  serviceaccount:
    enabled: false
  role:
    enabled: false
